BTBrl: Add Upstart script for Brltty
This is part of the work to add support for bluetooth refreshable braille displays
https://docs.google.com/document/d/1tYXsBQj4wbc8WdnlkMkzLhch4pm7W94bLzLCw_HPD8I/edit#
Chrome side change:
https://chromium-review.googlesource.com/c/chromium/src/+/1308986
BUG=chromium:882261
TEST=manual.

Change-Id: I695c73c781c3f806cea7d3a252ceb1057c6d9cb5
Reviewed-on: https://chromium-review.googlesource.com/1308895
Commit-Ready: ChromeOS CL Exonerator Bot <chromiumos-cl-exonerator@appspot.gserviceaccount.com>
Commit-Ready: David Tseng <dtseng@chromium.org>
Tested-by: David Tseng <dtseng@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>

diff --git a/app-accessibility/brltty/files/brltty b/app-accessibility/brltty/files/brltty
--- a/app-accessibility/brltty/files/brltty
+++ b/app-accessibility/brltty/files/brltty
@@ -5,6 +5,10 @@
 # found in the LICENSE file.
 
 # This script starts brltty in a minijail sandbox.
+if [ $# -ne 0 ]; then
+  echo "ERROR: $0 takes no arguments"
+  exit 1
+fi
 
 BRLTTY_RUNDIR=/run/brltty
 BRLAPI_SOCKETDIR="${BRLTTY_RUNDIR}"/BrlAPI
@@ -54,9 +58,14 @@ umask 0007
 log "Starting brltty, device: ${BRLTTY_BRAILLE_DEVICE}, " \
     "driver: ${BRLTTY_BRAILLE_DRIVER}"
 
+# -d: device for accessing braille.
+if [ -n "${ADDRESS}" ]; then
+  set -- "$@" -d "bluetooth:${ADDRESS}"
+fi
+
 # Start brltty in the jail.
-# The options are:
+# The options used below are:
 # - -q: No startup announcement of brltty's version on the braille display.
 # - -E: Get some arguments (driver, device, etc) from the environment.
-exec /sbin/minijail0 -u brltty -g brltty -G -- \
-  /bin/brltty -q -E -P${BRLTTY_PID_FILE}
+# - -n: makes Brltty run without forking (keeping this job started/stoppable).
+exec /sbin/minijail0 -u brltty -g brltty -G -- /bin/brltty -q -E -n "$@"
