infineon-firmware-updater: Request TPM clear in recovery mode.
When handling a TPM firmware update retry in recovery mode, the
existing code that clears the TPM is known to fail because the TPM
won't handle the respective commands in bootloader mode. It's still
possible a TPM owner is present, and it'll survive if the retry
completes successfully. As a result, the SRK from before the update
would be carried over, which we must not allow. To address this,
request the firmware to preform a TPM clear unconditionally before
starting the update so we have reasonable confidence the TPM will be
in a good state after update installation and reboot.

BUG=chromium:854576
TEST=Manual, see bug.

Change-Id: Ief6e065ac7b2e5c987abfc335e13823c4a21702c
Reviewed-on: https://chromium-review.googlesource.com/1108117
Commit-Ready: Mattias Nissler <mnissler@chromium.org>
Tested-by: Mattias Nissler <mnissler@chromium.org>
Reviewed-by: Andrey Pronin <apronin@chromium.org>

diff --git a/chromeos-base/infineon-firmware-updater/files/tpm-firmware-updater b/chromeos-base/infineon-firmware-updater/files/tpm-firmware-updater
--- a/chromeos-base/infineon-firmware-updater/files/tpm-firmware-updater
+++ b/chromeos-base/infineon-firmware-updater/files/tpm-firmware-updater
@@ -148,33 +148,33 @@ validate_attempt() {
 # Prepares the TPM before installing the update.
 prepare_tpm() {
   local tpm_auth_mechanism="$1"
-  case "${tpm_auth_mechanism}" in
-    # In case of owner-authorized updates:
-    # Request another TPM reset to take place after installing the update. This
-    # is important because owner-authorized update carries over some state
-    # (notably the SRK) which we specifically don't want to happen.
-    tpm12-takeownership|tpm12-ownerauth)
-      crossystem clear_tpm_owner_request=1
-      ;;
 
-    # In case of PP-authorized updates:
-    # The PP update still fails if the TPM is owned. Clear the TPM owner
-    # before the update. Do it on a "best effort" basis, ignoring any errors. If
-    # the TPM is in failed selftest mode, the commands will actually fail, but
-    # the firmware update can still be installed. If anything else fails and the
-    # TPM is left in non-updatable state, infineon-firmware-updater will detect
-    # the problem and report an error, which causes an error screen to be shown
-    # to the user.
-    tpm12-PP)
-      (
-        set +e
-        tpmc ppon
-        tpmc clear
-        tpmc enable
-        tpmc activate
-      ) || :
-      ;;
-  esac
+  # Request another TPM reset to take place after installing the update. This
+  # is important because the update carries over some state (notably the SRK)
+  # which we specifically don't want to happen.
+  #
+  # This is necessary for owner-authorized updating where the SRK is known to be
+  # present and must be cleared. It's also necessary for PP-authorized update
+  # retries in recovery mode, because the retry will keep TPM ownership intact
+  # and the TPM clear attempt below fails if the TPM is in failed selftest mode.
+  crossystem clear_tpm_owner_request=1
+
+  # If the TPM is owned, the PP-authorized update fails, so clear the TPM owner
+  # before the update. Do it on a "best effort" basis, ignoring any errors. If
+  # the TPM is in failed selftest mode, the commands will actually fail, but the
+  # firmware update can still be installed. If anything else fails and the TPM
+  # is left in non-updatable state, infineon-firmware-updater will detect the
+  # problem and report an error, which causes an error screen to be shown to the
+  # user.
+  if [ "${tpm_auth_mechanism}" = "tpm12-PP" ]; then
+    (
+      set +e
+      tpmc ppon
+      tpmc clear
+      tpmc enable
+      tpmc activate
+    ) || :
+  fi
 }
 
 # Fires off the firmware updater to install the update. Writes progress
